movie_site/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')), 
]

movie_site/pybo/urls.py
from django.urls import path

from .views import base_views

app_name = 'pybo'

urlpatterns = [
    #base_views.py
    path('', base_views.index, name='index'),
    path('movie_code=<int:movie_code>/', base_views.detail, name='detail'),
    path('review_code=<int:review_code>/', base_views.review, name='review'),
]

movie_site/pybo/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Actor(models.Model):
    actor_code = models.IntegerField(primary_key=True)
    actor_name = models.CharField(max_length=100, blank=True, null=True)
    original_actor_name = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'actor'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Director(models.Model):
    director_code = models.IntegerField(primary_key=True)
    director_name = models.CharField(max_length=100, blank=True, null=True)
    original_director_name = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'director'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Image(models.Model):
    movie_code = models.OneToOneField('Movie', models.DO_NOTHING, db_column='movie_code', primary_key=True)
    image_url = models.CharField(max_length=512)

    class Meta:
        managed = False
        db_table = 'image'
        unique_together = (('movie_code', 'image_url'),)


class Jenre(models.Model):
    movie_code = models.OneToOneField('Movie', models.DO_NOTHING, db_column='movie_code', primary_key=True)
    jenre_name = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = 'jenre'
        unique_together = (('movie_code', 'jenre_name'),)


class Movie(models.Model):
    movie_code = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=100, blank=True, null=True)
    original_title = models.CharField(max_length=100, blank=True, null=True)
    opening_date = models.DateTimeField(blank=True, null=True)
    playing_time = models.IntegerField(blank=True, null=True)
    domestic_rate = models.CharField(max_length=10, blank=True, null=True)
    foreign_rate = models.CharField(max_length=10, blank=True, null=True)
    subtitle = models.CharField(max_length=200, blank=True, null=True)
    content = models.CharField(max_length=2000, blank=True, null=True)
    poster_url = models.CharField(max_length=512, blank=True, null=True)
    audience_rate = models.FloatField(blank=True, null=True)
    journalist_rate = models.FloatField(blank=True, null=True)
    netizen_rate = models.FloatField(blank=True, null=True)
    audience_count = models.IntegerField(blank=True, null=True)
    journalist_count = models.IntegerField(blank=True, null=True)
    netizen_count = models.IntegerField(blank=True, null=True)
    cumulative_audience = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'movie'


class MovieActor(models.Model):
    movie_code = models.OneToOneField(Movie, models.DO_NOTHING, db_column='movie_code', primary_key=True)
    actor_code = models.ForeignKey(Actor, models.DO_NOTHING, db_column='actor_code')
    cast = models.CharField(max_length=5, blank=True, null=True)
    role = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'movie_actor'
        unique_together = (('movie_code', 'actor_code'),)


class MovieDirector(models.Model):
    movie_code = models.OneToOneField(Movie, models.DO_NOTHING, db_column='movie_code', primary_key=True)
    director_code = models.ForeignKey(Director, models.DO_NOTHING, db_column='director_code')

    class Meta:
        managed = False
        db_table = 'movie_director'
        unique_together = (('movie_code', 'director_code'),)


class MovieReview(models.Model):
    movie_code = models.OneToOneField(Movie, models.DO_NOTHING, db_column='movie_code', primary_key=True)
    review_code = models.ForeignKey('Review', models.DO_NOTHING, db_column='review_code')

    class Meta:
        managed = False
        db_table = 'movie_review'
        unique_together = (('movie_code', 'review_code'),)


class Nation(models.Model):
    movie_code = models.OneToOneField(Movie, models.DO_NOTHING, db_column='movie_code', primary_key=True)
    country = models.CharField(max_length=15)

    class Meta:
        managed = False
        db_table = 'nation'
        unique_together = (('movie_code', 'country'),)


class Point(models.Model):
    movie_code = models.OneToOneField(Movie, models.DO_NOTHING, db_column='movie_code', primary_key=True)
    point_id = models.CharField(max_length=30)
    point_content = models.CharField(max_length=500, blank=True, null=True)
    point_date = models.DateTimeField(blank=True, null=True)
    point_good = models.IntegerField(blank=True, null=True)
    point_bad = models.IntegerField(blank=True, null=True)
    point_star = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'point'
        unique_together = (('movie_code', 'point_id'),)


class Review(models.Model):
    review_code = models.IntegerField(primary_key=True)
    review_id = models.CharField(max_length=30, blank=True, null=True)
    review_title = models.CharField(max_length=100, blank=True, null=True)
    review_content = models.CharField(max_length=2000, blank=True, null=True)
    review_date = models.DateTimeField(blank=True, null=True)
    review_lookup = models.IntegerField(blank=True, null=True)
    review_recommend = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'review'


class Review2(models.Model):
    review_code = models.OneToOneField(Review, models.DO_NOTHING, db_column='review_code', primary_key=True)
    review2_id = models.CharField(max_length=30)
    review2_content = models.CharField(max_length=500, blank=True, null=True)
    review2_date = models.DateTimeField(blank=True, null=True)
    review2_good = models.IntegerField(blank=True, null=True)
    review2_bad = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'review2'
        unique_together = (('review_code', 'review2_id'),)


class Video(models.Model):
    movie_code = models.OneToOneField(Movie, models.DO_NOTHING, db_column='movie_code', primary_key=True)
    video_url = models.CharField(max_length=512)
    video_title = models.CharField(max_length=30, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'video'
        unique_together = (('movie_code', 'video_url'),)

movie_site/pybo/views/base_views.py
# import logging

from django.shortcuts import render
from ..models import Movie, Actor, MovieActor, Director, MovieDirector, \
                    Image, Video, Jenre, Nation, Point, Review, MovieReview, Review2
from django.core.paginator import Paginator  
from django.db.models import Q

# logger = logging.getLogger('pybo')

def index(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    akw = request.GET.get('akw', '') # 배우 검색어
    dkw = request.GET.get('dkw', '') # 감독 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'audience_rate':
        movie_list = Movie.objects.order_by('-audience_rate')
    elif so == 'journalist_rate':
        movie_list = Movie.objects.order_by('-journalist_rate')
    elif so == 'netizen_rate':
        movie_list = Movie.objects.order_by('-netizen_rate')
    elif so == 'title':
        movie_list = Movie.objects.order_by('title')
    else:  # 이름순
        movie_list = Movie.objects.order_by('-opening_date')

    # 검색
    if kw:
        movie_list = movie_list.filter(
            Q(title__icontains=kw) |
            Q(original_title__icontains=kw) |
            Q(content__icontains=kw) |
            Q(subtitle__icontains=kw)
        ).distinct()
    
    if akw:
        actors = Actor.objects.filter(Q(actor_name__icontains=akw)).values('actor_code')
        movie_codes = MovieActor.objects.filter(actor_code__in=actors).values('movie_code')
        movie_list = movie_list.filter(
            movie_code__in=movie_codes
        ).distinct()
    
    if dkw:
        directors = Director.objects.filter(Q(director_name__icontains=dkw)).values('director_code')
        movie_codes2 = MovieDirector.objects.filter(director_code__in=directors).values('movie_code')
        movie_list = movie_list.filter(
            movie_code__in=movie_codes2
        ).distinct()
        
    paginator = Paginator(movie_list, 20)  # 페이지당 20개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'movie_list': page_obj, 'page':page, 'kw':kw, 'so':so, 'akw':akw, 'dkw':dkw}
    return render(request, 'pybo/movie_list.html', context)
def detail(request, movie_code):
    movie = Movie.objects.get(movie_code=movie_code)
    jenre = Jenre.objects.filter(movie_code=movie_code)
    nation = Nation.objects.filter(movie_code=movie_code)
    movie_actor = MovieActor.objects.filter(movie_code=movie_code)
    movie_director = MovieDirector.objects.filter(movie_code=movie_code)
    movie_review = MovieReview.objects.filter(movie_code=movie_code)
    image  = Image.objects.filter(movie_code=movie_code)
    video  = Video.objects.filter(movie_code=movie_code)
    point = Point.objects.filter(movie_code=movie_code)
    context = {'movie': movie, 'jenre': jenre, 'nation': nation, 'movie_actor':movie_actor, 'movie_director':movie_director, 'movie_review':movie_review, 'image': image, 'video': video, 'point':point}
    return render(request, 'pybo/movie_detail.html', context)
def review(request, review_code):
    review = Review.objects.get(review_code=review_code)
    review2 = Review2.objects.filter(review_code=review_code)
    context = {'review':review, 'review2':review2}
    return render(request, 'pybo/movie_review.html', context)

movie_site/templates/pybo/movie_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 제목 및 기본정보 -->
    <h1 class="border-bottom py-2">{{ movie.title }}</h1>
    <h5 class="border-bottom py-2">{{ movie.original_title }}</h5>
    {% if movie.poster_url %}
    <div class='poster'>
        <img src= {{movie.poster_url}} style ="display:block;margin:0 auto;width:12em;">
    </div>
    {% endif %}
    <div class="card my-3">
        <div class="card-body">
            {% if movie.opening_date %}
            <div class="card-text" style="white-space: pre-line;">개봉일 : {{ movie.opening_date }}</div>
            {% endif %}
            {% if movie.playing_time %}
            <div class="card-text" style="white-space: pre-line;">런타임 : {{ movie.playing_time }}분</div>
            {% endif %}
            {% if movie.domestic_rate or movie.foreign_rate %}
            <div class="card-text" style="display:inline;">등급 :</div>
            {% endif %}
            {% if movie.domestic_rate %}
            <span> [국내] {{ movie.domestic_rate }} </span>
            {% endif %}
            {% if movie.foreign_rate %}
            <span> [해외] {{ movie.foreign_rate }}</span>
            {% endif %}
            <div style="white-space: pre-line;"> </div>
            {% if movie.cumulative_audience %}
            <div class="card-text" style="white-space: pre-line;">누적 관객 수 : {{ movie.cumulative_audience }}명</div>
            {% endif %}
            {% if jenre %}
            <div class="card-text" style="display:inline;">장르 :</div>
            {% for jnr in jenre %}
            <span> {{ jnr.jenre_name }}</span>
            {% endfor %}
            {% endif %}
            {% if nation %}
            <div style="white-space: pre-line;"> </div>
            <div class="card-text" style="display:inline;">국가 :</div>
            {% for ctr in nation %}
            <span> {{ ctr.country }}</span>
            {% endfor %}
            {% endif %}
            
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    세부사항
                </div>
            </div>
        </div>
    </div>
    <!-- 별점 -->
    <h5 class="border-bottom my-3 py-2">별점</h5>
    <div class="card my-3">
        <div class="card-body">
            {% if movie.audience_rate or movie.journalist_rate or movie.netizen_rate %}
                {% if movie.audience_rate %}
                <div style="white-space: pre-line;"> </div>
                <div class="card-text" style="display:inline;">관람객 : {{ movie.audience_rate }}점</div>
                {% if movie.audience_count %}
                <span> | {{ movie.audience_count }}명</span>
                {% endif %}
                {% endif %}
                {% if movie.journalist_rate %}
                <div style="white-space: pre-line;"> </div>
                <div class="card-text" style="display:inline;">기자/평론가 : {{ movie.journalist_rate }}점</div>
                {% if movie.journalist_count %}
                <span> | {{ movie.journalist_count }}명</span>
                {% endif %}
                {% endif %}
                {% if movie.netizen_rate %}
                <div style="white-space: pre-line;"> </div>
                <div class="card-text" style="display:inline;">네티즌 : {{ movie.netizen_rate }}점</div>
                {% if movie.netizen_count %}
                <span> | {{ movie.netizen_count }}명</span>
                {% endif %}
                {% endif %}
            {% else %}
                <div class="card-text" style="white-space: pre-line;">등록된 별점이 없습니다.</div>
            {% endif %}
        </div>
    </div>
    <!-- 내용 -->
    {% if movie.subtitle %}
    <h5 class="border-bottom my-3 py-2">{{movie.subtitle}}</h5>
    {% else %}
    <h5 class="border-bottom my-3 py-2">줄거리</h5>
    {% endif %}
    <div class="card my-3">
        <div class="card-body">
            {% if movie.content %}
            <div class="card-text" style="white-space: pre-line;">{{ movie.content }}</div>
            {% else %}
            <div class="card-text" style="white-space: pre-line;">등록된 줄거리가 없습니다.</div>
            {% endif %}
        </div>
    </div>
    <!-- 배우 -->
    <h5 class="border-bottom my-3 py-2">배우</h5>
    <div class="card my-3">
        <div class="card-body">
            {% if movie_actor %}
            {% for act in movie_actor %}
            <div style="white-space: pre-line;"> </div>
            <div class="card-text" style="display:inline;">{{ act.actor_code.actor_name }} </div>
            {% if act.actor_code.original_actor_name %}
            <span>| {{ act.actor_code.original_actor_name }}</span>
            {% endif %}
            {% if act.cast %}
            <span>| {{ act.cast }}</span>
            {% endif %}
            {% if act.role %}
            <span>| {{ act.role }}</span>
            {% endif %}
            {% endfor %}
            {% else %}
            <div class="card-text" style="white-space: pre-line;">등록된 배우가 없습니다.</div>
            {% endif %}
        </div>
    </div>
    <!-- 감독 -->
    <h5 class="border-bottom my-3 py-2">감독</h5>
    <div class="card my-3">
        <div class="card-body">
            {% if movie_director %}
            {% for drt in movie_director %}
            <div style="white-space: pre-line;"> </div>
            <div class="card-text" style="display:inline;">{{ drt.director_code.director_name }} </div>
            {% if drt.director_code.original_director_name %}
            <span>| {{ drt.director_code.original_director_name }}</span>
            {% endif %}
            {% endfor %}
            {% else %}
            <div class="card-text" style="white-space: pre-line;">등록된 감독이 없습니다.</div>
            {% endif %}
        </div>
    </div>
    <!-- 비디오 -->
    <h5 class="border-bottom my-3 py-2">비디오</h5>
    <div class="card my-3">
        <div class="card-body">
            {% if video %}
            <div class='vd'>
                {% for vd in video %}
                <div class="card-text" style="display:inline;">{{ vd.video_title}} |</div>
                    <a href="{{ vd.video_url }}"> 영상 링크</a>
                <div style="white-space: pre-line;"> 
                </div>
                {% endfor %}
            </div>
            {% else %}
            <div class="card-text" style="white-space: pre-line;">등록된 비디오가 없습니다.</div>
            {% endif %}
        </div>
    </div>
    <!-- 이미지 -->
    <h5 class="border-bottom my-3 py-2">포토</h5>
    {% if image %}
    <div class='imgs'>
        {% for img in image %}
        <img src= {{img.image_url}}>
        {% endfor %}
    </div>
    {% else %}
    <div class="card-text" style="white-space: pre-line;">등록된 사진이 없습니다.</div>
    {% endif %}
    <!-- 리뷰 -->
    <h5 class="border-bottom my-3 py-2">리뷰</h5>
    <div class="card my-3">
        <div class="card-body">
            {% if movie_review %}
            {% for mr in movie_review %}
            <div class="card-text" style="display:inline;">{{ mr.review_code.review_id }} </div>
            <span> | {{ mr.review_code.review_title }}</span>
            <a href="{% url 'pybo:review' mr.review_code.review_code %}"> 리뷰보기</a>
            {% if mr.review_code.review_date %}
            <span> | {{ mr.review_code.review_date }}</span>
            {% endif %}
            <div style="white-space: pre-line;"> </div>
            {% if mr.review_code.review_lookup %}
            <span>조회 : {{ mr.review_code.review_lookup }}</span>
            {% endif %}
            {% if mr.review_code.review_recommend %}
            <span> | 추천 : {{ mr.review_code.review_recommend }}</span>
            {% endif %}
            <div style="white-space: pre-line;"> 
            </div>
            {% endfor %}
            {% else %}
            <div class="card-text" style="white-space: pre-line;">등록된 리뷰가 없습니다.</div>
            {% endif %}
        </div>
    </div>
    <!-- 평점 -->
    <h5 class="border-bottom my-3 py-2">평점</h5>
    <div class="card my-3">
        <div class="card-body">
            {% if point %}
            {% for pt in point %}
            <div class="card-text" style="display:inline;">{{ pt.point_id }} </div>
            {% if pt.point_star %}
            <span> | {{ pt.point_star }}점</span>
            {% endif %}
            {% if pt.point_content %}
            <span> | {{ pt.point_content }}</span>
            {% endif %}
            <div style="white-space: pre-line;"> </div>
            {% if pt.point_date %}
            <span>{{ pt.point_date }}</span>
            {% endif %}
            {% if pt.point_good %}
            <span> | 추천 : {{ pt.point_good }}</span>
            {% endif %}
            {% if pt.point_bad %}
            <span> | 비추천 : {{ pt.point_bad }}</span>
            {% endif %}
            <div style="white-space: pre-line;"> 
            </div>
            {% endfor %}
            {% else %}
            <div class="card-text" style="white-space: pre-line;">등록된 평점이 없습니다.</div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

movie_site/templates/pybo/movie_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <div class="row justify-content-between my-3">
        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
                <option value="audience_rate" {% if so == 'audience_rate' %}selected{% endif %}>관람객 평점순</option>
                <option value="netizen_rate" {% if so == 'netizen_rate' %}selected{% endif %}>네티즌 평점순</option>
                <option value="journalist_rate" {% if so == 'journalist_rate' %}selected{% endif %}>기자 평점순</option>
                <option value="title" {% if so == 'title' %}selected{% endif %}>이름순</option>
            </select>
        </div>
        <div class="col-3">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control kw" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search1">영화 찾기</button>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="input-group">
                <input type="text" id="search_akw" class="form-control akw" value="{{ akw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search2">배우 찾기</button>
                </div>
            </div>
        </div>
        <div class="col-3">
            <div class="input-group">
                <input type="text" id="search_dkw" class="form-control dkw" value="{{ dkw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search3">감독 찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="table-dark, text-center">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>원어제목</th>
            <th>개봉일</th>
        </tr>
        </thead>
        <tbody>
        {% if movie_list %}
        {% for movie in movie_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                <!-- {{ movie_list.paginator.count|add:movie_list.start_index|sub:22|add:forloop.counter0 }} -->
                {{ movie_list.start_index|add:forloop.counter0 }}
            </td>
            <td>
                <a href="{% url 'pybo:detail' movie.movie_code %}">{{ movie.title }}</a>
            </td>
            <td>
                <a href="{% url 'pybo:detail' movie.movie_code %}">{{ movie.original_title }}</a>
            </td>
            
            <td>{{ movie.opening_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">영화가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if movie_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?kw={{ kw }}&akw={{ akw }}&dkw={{ dkw }}&page={{ movie_list.previous_page_number }}&so={{ so }}">이전</a>
            <!-- <a class="page-link" data-page="{{ movie_list.previous_page_number }}"
           href="javascript:void(0)">이전</a> -->
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            <!-- <a class="page-link" tabindex="-1" aria-disabled="true"
               href="javascript:void(0)">이전</a> -->
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in movie_list.paginator.page_range %}
        {% if page_number >= movie_list.number|add:-5 and page_number <= movie_list.number|add:5 %}
        {% if page_number == movie_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?kw={{ kw }}&akw={{ akw }}&dkw={{ dkw }}&page={{ page_number }}&so={{ so }}">{{ page_number }}</a>
            <!-- <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a> -->
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?kw={{ kw }}&akw={{ akw }}&dkw={{ dkw }}&page={{ page_number }}&so={{ so }}">{{ page_number }}</a>
            <!-- <a class="page-link" data-page="{{ page_number }}"
           href="javascript:void(0)">{{ page_number }}</a> -->
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if movie_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?kw={{ kw }}&akw={{ akw }}&dkw={{ dkw }}&page={{ movie_list.next_page_number }}&so={{ so }}">다음</a>
            <!-- <a class="page-link" data-page="{{ movie_list.next_page_number }}"
           href="javascript:void(0)">다음</a> -->
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            <!-- <a class="page-link" tabindex="-1" aria-disabled="true"
            href="javascript:void(0)">다음</a> -->
        </li>
        {% endif %}
        
    </ul>
    <!-- 페이징처리 끝 -->
</div>
<form id="searchForm" method="get" action="{% url 'pybo:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="akw" name="akw" value="{{ akw|default_if_none:'' }}">
    <input type="hidden" id="dkw" name="dkw" value="{{ dkw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search1").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

    $("#btn_search2").on('click', function() {
        $("#akw").val($(".akw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

    $("#btn_search3").on('click', function() {
        $("#dkw").val($(".dkw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}